// This is a test harness for your module
// You should do something interesting in this harness 
// to test out the module and to provide instructions 
// to users on how to use it by example.


// Sorry, I can`t put a fully functional demo here.
// How your app gets the apiKey, token & sessionId
// is really down to you, for most uses they will
// be generated by a web server and fetched using
// a http request.

// Below is just the syntax for calling the module.
// It works differently to TokBox`s own ios module
// the view layout and video size are hard coded
// as that suited my needs, but passing them in as
// parameters would take very little modification
// of the code.

var apiKey = 'STRING - APIKEY';
var token = 'STRING - TOKEN';
var sessionId = 'STRING - SESSIONID';

var opentok = require('com.phc.opentok');
opentok.start({
	success:function(data) {
		Ti.API.info('OPENTOK SUCCESS, DATA = '+JSON.stringify(data));
	},
	error:function(err) {
		alert("Error!! " + err);
	},
	cancel:function() {
		alert("cancel");
	}
}, apiKey, token, session_id);

